export const catcher = err => {
    console.error(err);
}